---
- hosts: all
  vars_files:
    - defaults/main.yml
  pre_tasks:
    - name: "Installing which on CentOS"
      action: yum
              name={{ item }}
              state=installed
      with_items:
        - net-tools
        - which
      when: ansible_os_family == "RedHat"
    - name: "Installing which on NON-CentOS"
      action: apt
              name={{ item }}
              state=installed
      with_items:
        - net-tools
      when: ansible_os_family == "Debian"
  tasks:
    - include: tasks/main.yml
